version: '3.8'

services:
  mongo: 
    image: mongo:6.0
    command: mongod --replSet rs0 --bind_ip_all
    container_name: ecommerce
    ports:
      - "27017:27017"
    volumes:
      - ./backend/src/config/database/db:/data/db
    
  backend: 
    build: 
      context: ./backend
      dockerfile: DOCKERFILE
    container_name: backend
    environment:
      - PORT={BACKEND_PORT}
      - MONGO_URI={DB_URI}
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
  
  frontend: 
    build:
      context: ./frontend
      dockerfile: DOCKERFILE
    container_name: frontend
    ports:
      - "{FRONTEND_PORT}:{FRONTEND_PORT}"
    volumes:
      - ./fronend/app
      - /app/node_modules
    restart: always
    networks:
      - react-express:
          driver: bridge
    depends_on:
      - backend

networks:
  react-express:
  express-mongo: